### ISSUE TITLE
总是运行报错怎么办呀，谢谢

### ISSUE THREAD

**Issue by crankler** [LUCY78765580/Python-web-scraping#2]
Traceback (most recent call last):
  File "C:/Users/chengxiang/Desktop/test3/222", line 112, in <module>
    spider = Spider()
  File "C:/Users/chengxiang/Desktop/test3/222", line 15, in __init__
    self.keyword=raw_input(u'欢迎使用 pexels 图片搜索下载神器\n请输入搜索关键词(英文)：')
NameError: name 'raw_input' is not defined

**Comment by lbdong22** [comment]
"C:\Program Files\Anaconda3\envs\VNPY\python.exe" C:/VNPY/study/__init__.py
Traceback (most recent call last):
  File "C:/VNPY/study/__init__.py", line 112, in <module>
    spider=Spider()
  File "C:/VNPY/study/__init__.py", line 15, in __init__
    self.keyword=raw_input(u'欢迎使用 pexels 图片搜索下载神器\n请输入搜索关键词(英文)：')
NameError: name 'raw_input' is not defined

**Comment by SHENG-KAI-HUANG** [comment]
嘗試用python2執行，不要用python3，試試看?
補充，pixels似乎增加了阻止爬蟲的機制，可能還要再注意看看
